version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
    groups:
      prod:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      prod:
        applies-to: version-updates
        patterns:
          - "aiofiles"
          - "yarl"
          - "backoff"
          - "aiohttp"
          - "paho-mqtt"
      dev:
        applies-to: version-updates
        exclude-patterns:
          - "aiofiles"
          - "yarl"
          - "backoff"
          - "aiohttp"
          - "paho-mqtt"