# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [pre-commit, commit-msg]

default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: debug-statements
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.24.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: lint
        name: Run lint with ruff
        language: system
        types: [python]
        entry: poetry run ruff --fix
        exclude: ^docs\/conf.py$
      - id: format
        name: Run lint with ruff
        language: system
        types: [python]
        entry: poetry run ruff format --fix
