name: On pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - dev

env:
  DEFAULT_PYTHON: 3.12

jobs:

  python_checks:
#    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    name: Python Checks
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: Work dependencies with poetry
        run: |
          poetry install --with dev
      - name: Running Validations
        run: |
          poetry run pre-commit run
      - name: Checking commit messages to ${{github.head_ref}}
        run: |
          poetry run cz check --allow-abort --rev-range  ${{github.base_ref}}..HEAD
