name: Update Dev Branch
on:
    workflow_run:
      workflows: [Build and Deploy]
      types: [completed]
      branches: [main]
    
permissions: 
  contents: write

jobs:
    sync:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@main
          with:
            fetch-depth: 0
            token: ${{ secrets.ALT_TOKEN }}
        - name: Setup Git User
          run: |
            git config user.name "GitHub Action"
            git config user.email "<EMAIL>"

        - name: Update Test Branch
          run: |
            git checkout main
            git fetch origin
            git checkout dev
            git pull
            git merge origin/main
            git push origin dev